on:
  push:
    tags:
      - '*.*.*'
jobs:
  auto-tag:
    name: Auto-tag
    runs-on: ubuntu-latest
    steps:
      - name: Auto-tag
        uses: emteknetnz/gha-auto-tag@main
        with:
          ref: ${{ github.ref }}
          sha: ${{ github.sha }}
